spring:
  application.name: kale-kaj-agent
  ai:
    vertex:
      ai:
        gemini:
          project-id: ai-circle-2025-cluster-34390
          location: europe-north1
          chat:
            options:
              model: gemini-2.5-pro
#          transport: rest
#  main:
#    banner-mode: off
#  http:
#    client:
#      factory: jdk

embabel:
  models:
    default-llm: gemini-2.5-pro
